# Generated by Django 3.1 on 2020-08-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200810_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='total_likes',
        ),
    ]
