# Generated by Django 3.1 on 2020-08-12 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200811_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
