# Generated by Django 3.1 on 2020-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200812_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
